### ISSUE TITLE
QRcode登入錯誤

### ISSUE THREAD

**Issue by mnb8849123** [kevin940726/BeanfunLogin#26]
1. 作業系統版本： WIN 7
2. 是否安裝.net framework 4.5以上： (yes)
3. 程式資料夾是否有解壓縮出四個dll檔： (yes)
4. Beanfun網站是否能正常登入和啟動遊戲： (yes)
5. 是否已經依照上面兩個問與答嘗試排除問題： (yes)
6. 是否有防毒軟體跳出通知或偵測訊息： (no)
7. 使用舊版是否能正常運作： (no)
8. 是否刪除程式，重新下載v1.9.3還是出現問題： (yes)
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： (yes)
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：
當我嘗試用QRcode登入時都會顯示''AKeyParseFailed''，看了巴哈版上也有人也出現這個問題，希望您能夠修正這個問題，感謝您。
![login fail](https://cloud.githubusercontent.com/assets/25954258/23211023/fb831fd6-f93a-11e6-9b22-9319e5515635.jpg)

**Comment by kevin940726** [comment]
@xnum  any idea?

**Comment by xnum** [comment]
Gamania updated its login procedure today, a new feature has been added.
You can determined allow or deny every login request.
browser is waiting for this response and get akey.
Since this feature seems not very stable, even be changed,
it's not necessary to be fixed now.
I'm busy at writing thesis and finding job, but I will try to fix it when I am free.

**Comment by kevin940726** [comment]
LGTM,
thanks for your awesome support!
Good luck to your thesis! I'm busy finding job too :sweat_smile:
